spring:
  profiles:
    active: local # default
    group:
      local:  # local, common profile을 그룹지어 함께 어플리케이션 구동
        - oauth

  datasource:
    url: jdbc:h2:tcp://localhost/~/tastyjapan;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver


  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: create-drop

    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100

logging:
  level:
    # Logger에 sql문이 찍힌다.
    org.hibernate.SQL: debug
    p6spy: info
